/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { JobPosting } from "./JobPosting";
import { JobPostingCountArgs } from "./JobPostingCountArgs";
import { JobPostingFindManyArgs } from "./JobPostingFindManyArgs";
import { JobPostingFindUniqueArgs } from "./JobPostingFindUniqueArgs";
import { CreateJobPostingArgs } from "./CreateJobPostingArgs";
import { UpdateJobPostingArgs } from "./UpdateJobPostingArgs";
import { DeleteJobPostingArgs } from "./DeleteJobPostingArgs";
import { Employer } from "../../employer/base/Employer";
import { JobPostingService } from "../jobPosting.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => JobPosting)
export class JobPostingResolverBase {
  constructor(
    protected readonly service: JobPostingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "JobPosting",
    action: "read",
    possession: "any",
  })
  async _jobPostingsMeta(
    @graphql.Args() args: JobPostingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [JobPosting])
  @nestAccessControl.UseRoles({
    resource: "JobPosting",
    action: "read",
    possession: "any",
  })
  async jobPostings(
    @graphql.Args() args: JobPostingFindManyArgs
  ): Promise<JobPosting[]> {
    return this.service.jobPostings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => JobPosting, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "JobPosting",
    action: "read",
    possession: "own",
  })
  async jobPosting(
    @graphql.Args() args: JobPostingFindUniqueArgs
  ): Promise<JobPosting | null> {
    const result = await this.service.jobPosting(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => JobPosting)
  @nestAccessControl.UseRoles({
    resource: "JobPosting",
    action: "create",
    possession: "any",
  })
  async createJobPosting(
    @graphql.Args() args: CreateJobPostingArgs
  ): Promise<JobPosting> {
    return await this.service.createJobPosting({
      ...args,
      data: {
        ...args.data,

        employer: args.data.employer
          ? {
              connect: args.data.employer,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => JobPosting)
  @nestAccessControl.UseRoles({
    resource: "JobPosting",
    action: "update",
    possession: "any",
  })
  async updateJobPosting(
    @graphql.Args() args: UpdateJobPostingArgs
  ): Promise<JobPosting | null> {
    try {
      return await this.service.updateJobPosting({
        ...args,
        data: {
          ...args.data,

          employer: args.data.employer
            ? {
                connect: args.data.employer,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => JobPosting)
  @nestAccessControl.UseRoles({
    resource: "JobPosting",
    action: "delete",
    possession: "any",
  })
  async deleteJobPosting(
    @graphql.Args() args: DeleteJobPostingArgs
  ): Promise<JobPosting | null> {
    try {
      return await this.service.deleteJobPosting(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Employer, {
    nullable: true,
    name: "employer",
  })
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "read",
    possession: "any",
  })
  async getEmployer(
    @graphql.Parent() parent: JobPosting
  ): Promise<Employer | null> {
    const result = await this.service.getEmployer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
