/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { JobSeekerService } from "../jobSeeker.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobSeekerCreateInput } from "./JobSeekerCreateInput";
import { JobSeeker } from "./JobSeeker";
import { JobSeekerFindManyArgs } from "./JobSeekerFindManyArgs";
import { JobSeekerWhereUniqueInput } from "./JobSeekerWhereUniqueInput";
import { JobSeekerUpdateInput } from "./JobSeekerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JobSeekerControllerBase {
  constructor(
    protected readonly service: JobSeekerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JobSeeker })
  @nestAccessControl.UseRoles({
    resource: "JobSeeker",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createJobSeeker(
    @common.Body() data: JobSeekerCreateInput
  ): Promise<JobSeeker> {
    return await this.service.createJobSeeker({
      data: {
        ...data,

        internship: data.internship
          ? {
              connect: data.internship,
            }
          : undefined,

        job: data.job
          ? {
              connect: data.job,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        education: true,
        id: true,

        internship: {
          select: {
            id: true,
          },
        },

        job: {
          select: {
            id: true,
          },
        },

        resume: true,
        skillSet: true,
        skills: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [JobSeeker] })
  @ApiNestedQuery(JobSeekerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "JobSeeker",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobSeekers(@common.Req() request: Request): Promise<JobSeeker[]> {
    const args = plainToClass(JobSeekerFindManyArgs, request.query);
    return this.service.jobSeekers({
      ...args,
      select: {
        createdAt: true,
        education: true,
        id: true,

        internship: {
          select: {
            id: true,
          },
        },

        job: {
          select: {
            id: true,
          },
        },

        resume: true,
        skillSet: true,
        skills: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JobSeeker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobSeeker",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobSeeker(
    @common.Param() params: JobSeekerWhereUniqueInput
  ): Promise<JobSeeker | null> {
    const result = await this.service.jobSeeker({
      where: params,
      select: {
        createdAt: true,
        education: true,
        id: true,

        internship: {
          select: {
            id: true,
          },
        },

        job: {
          select: {
            id: true,
          },
        },

        resume: true,
        skillSet: true,
        skills: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JobSeeker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobSeeker",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateJobSeeker(
    @common.Param() params: JobSeekerWhereUniqueInput,
    @common.Body() data: JobSeekerUpdateInput
  ): Promise<JobSeeker | null> {
    try {
      return await this.service.updateJobSeeker({
        where: params,
        data: {
          ...data,

          internship: data.internship
            ? {
                connect: data.internship,
              }
            : undefined,

          job: data.job
            ? {
                connect: data.job,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          education: true,
          id: true,

          internship: {
            select: {
              id: true,
            },
          },

          job: {
            select: {
              id: true,
            },
          },

          resume: true,
          skillSet: true,
          skills: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JobSeeker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobSeeker",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJobSeeker(
    @common.Param() params: JobSeekerWhereUniqueInput
  ): Promise<JobSeeker | null> {
    try {
      return await this.service.deleteJobSeeker({
        where: params,
        select: {
          createdAt: true,
          education: true,
          id: true,

          internship: {
            select: {
              id: true,
            },
          },

          job: {
            select: {
              id: true,
            },
          },

          resume: true,
          skillSet: true,
          skills: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
