/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { InternshipUpdateManyWithoutEmployersInput } from "./InternshipUpdateManyWithoutEmployersInput";
import { Type } from "class-transformer";
import { JobPostingUpdateManyWithoutEmployersInput } from "./JobPostingUpdateManyWithoutEmployersInput";
import { JobUpdateManyWithoutEmployersInput } from "./JobUpdateManyWithoutEmployersInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class EmployerUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactEmail?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => InternshipUpdateManyWithoutEmployersInput,
  })
  @ValidateNested()
  @Type(() => InternshipUpdateManyWithoutEmployersInput)
  @IsOptional()
  @Field(() => InternshipUpdateManyWithoutEmployersInput, {
    nullable: true,
  })
  internships?: InternshipUpdateManyWithoutEmployersInput;

  @ApiProperty({
    required: false,
    type: () => JobPostingUpdateManyWithoutEmployersInput,
  })
  @ValidateNested()
  @Type(() => JobPostingUpdateManyWithoutEmployersInput)
  @IsOptional()
  @Field(() => JobPostingUpdateManyWithoutEmployersInput, {
    nullable: true,
  })
  jobPostings?: JobPostingUpdateManyWithoutEmployersInput;

  @ApiProperty({
    required: false,
    type: () => JobUpdateManyWithoutEmployersInput,
  })
  @ValidateNested()
  @Type(() => JobUpdateManyWithoutEmployersInput)
  @IsOptional()
  @Field(() => JobUpdateManyWithoutEmployersInput, {
    nullable: true,
  })
  jobs?: JobUpdateManyWithoutEmployersInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  website?: string | null;
}

export { EmployerUpdateInput as EmployerUpdateInput };
